import React, { useEffect, useMemo, useState } from "react";
import { Activity, RefreshCw } from "lucide-react";
import { ResponsiveContainer, ComposedChart, XAxis, YAxis, Tooltip, CartesianGrid, Line, Bar, ReferenceArea, ReferenceLine, Cell } from "recharts";
import { registerSW } from "virtual:pwa-register";

const SYMBOL_OPTIONS=[{label:"BTC",value:"BTCUSDT"},{label:"ETH",value:"ETHUSDT"},{label:"SOL",value:"SOLUSDT"}];
const INTERVAL_OPTIONS=[{label:"15m",value:"15m"},{label:"1h",value:"1h"},{label:"4h",value:"4h"}];
const HIGHER_INTERVAL_MAP={"15m":["1h","4h"],"1h":["4h"],"4h":["1d"]};

const fmt=(v,d=2)=>v==null||Number.isNaN(v)?"-":Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d});
const fmtTime=(ts,i)=>{const d=new Date(ts);return i==="15m"||i==="1h"?`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`:`${d.getMonth()+1}/${d.getDate()}`};
const sma=(a,p)=>a.map((_,i)=>i+1<p?null:a.slice(i-p+1,i+1).reduce((x,y)=>x+y,0)/p);
function ema(v,p){if(!v.length)return[];const k=2/(p+1),r=[v[0]];for(let i=1;i<v.length;i++)r.push(v[i]*k+r[i-1]*(1-k));return r}
function rsi(cl,p=14){if(cl.length<p+1)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=cl[i]-cl[i-1];if(d>=0)g+=d;else l+=Math.abs(d)}let ag=g/p,al=l/p;for(let i=p+1;i<cl.length;i++){const d=cl[i]-cl[i-1],gg=d>0?d:0,ll=d<0?Math.abs(d):0;ag=(ag*(p-1)+gg)/p;al=(al*(p-1)+ll)/p}if(al===0)return 100;const rs=ag/al;return 100-100/(1+rs)}
function macd(cl){if(cl.length<35)return null;const e12=ema(cl,12),e26=ema(cl,26),m=cl.map((_,i)=>e12[i]-e26[i]),s=ema(m,9);return{macd:m.at(-1),signal:s.at(-1),histogram:m.at(-1)-s.at(-1)}}
function atr(cs,p=14){if(cs.length<p+1)return null;const tr=[];for(let i=1;i<cs.length;i++){const c=cs[i],pc=cs[i-1].close;tr.push(Math.max(c.high-c.low,Math.abs(c.high-pc),Math.abs(c.low-pc)))}const r=tr.slice(-p);return r.reduce((a,b)=>a+b,0)/r.length}
function swings(cs,l=3,r=3){const sh=[],sl=[];for(let i=l;i<cs.length-r;i++){let ih=true,il=true;for(let j=i-l;j<=i+r;j++){if(j===i)continue;if(cs[j].high>=cs[i].high)ih=false;if(cs[j].low<=cs[i].low)il=false}if(ih)sh.push({price:cs[i].high});if(il)sl.push({price:cs[i].low})}return{sh,sl}}
function dedupe(arr,g){const o=[];for(const x of arr)if(!o.some(y=>Math.abs(y.price-x.price)<g))o.push(x);return o}
function zone(c,a){const w=Math.max((a||c*0.008)*0.35,c*0.0025);return{low:c-w,high:c+w}}
function pivots(cs,price,a){const {sh,sl}=swings(cs,3,3);const gap=Math.max((a||price*0.01)*0.6,price*0.004), floor=Math.max((a||price*0.01)*0.8,price*0.006);
const ss=dedupe(cs.map(c=>({price:c.low})).filter(x=>x.price<price&&price-x.price>=floor*.3).sort((a,b)=>b.price-a.price),gap).slice(0,2);
const sr=dedupe(cs.map(c=>({price:c.high})).filter(x=>x.price>price&&x.price-price>=floor*.3).sort((a,b)=>a.price-b.price),gap).slice(0,2);
const ls=dedupe(sl.filter(x=>x.price<price&&price-x.price>=floor).sort((a,b)=>b.price-a.price),gap).slice(0,2);
const lr=dedupe(sh.filter(x=>x.price>price&&x.price-price>=floor).sort((a,b)=>a.price-b.price),gap).slice(0,2);
const ns=ls[0]?.price??ss[0]?.price??price*.985,nr=lr[0]?.price??sr[0]?.price??price*1.015,ss2=ls[1]?.price??ss[1]?.price??price*.97,sr2=lr[1]?.price??sr[1]?.price??price*1.03;
return{nearestSupport:ns,secondSupport:ss2,nearestResistance:nr,secondResistance:sr2,shortSupportZone:zone(ss[0]?.price??ns,a),shortResistanceZone:zone(sr[0]?.price??nr,a),structureSupportZone:zone(ls[0]?.price??ns,a),structureResistanceZone:zone(lr[0]?.price??nr,a)}}
function detectStructure(cs){const recent=cs.slice(-30),s=swings(recent,2,2),h=s.sh.slice(-3).map(x=>x.price),l=s.sl.slice(-3).map(x=>x.price);let structure="盤整";if(h.length>=2&&l.length>=2){if(h.at(-1)>h[0]&&l.at(-1)>l[0])structure="上升結構";else if(h.at(-1)<h[0]&&l.at(-1)<l[0])structure="下降結構"}return structure}
function volState(cs){if(cs.length<25)return"一般";const r=cs.slice(-20).map(c=>c.volume),avg=r.reduce((a,b)=>a+b,0)/r.length,last=cs.at(-1).volume;if(last>avg*1.6)return"放量";if(last<avg*.75)return"量縮";return"一般"}
function breakout(cs,lv,a){const last=cs.at(-1),prev=cs.at(-2),t=Math.max((a||last.close*.01)*.25,last.close*.0025);if(last.close>lv.structureResistanceZone.high+t&&prev.close<=lv.structureResistanceZone.high)return"向上突破";if(last.close<lv.structureSupportZone.low-t&&prev.close>=lv.structureSupportZone.low)return"向下跌破";if(last.low<=lv.structureSupportZone.high&&last.close>lv.structureSupportZone.high)return"回踩支撐中";if(last.high>=lv.structureResistanceZone.low&&last.close<lv.structureResistanceZone.low)return"反彈壓力中";return"區間內"}
function liqSweep(cs,lv,a){if(cs.length<3)return"無明顯掃流動性";const last=cs.at(-1),prev=cs.at(-2),b=Math.max((a||last.close*.01)*.2,last.close*.002);const sh=last.high>lv.structureResistanceZone.high+b&&last.close<lv.structureResistanceZone.high,sl=last.low<lv.structureSupportZone.low-b&&last.close>lv.structureSupportZone.low;if(sh&&last.close<prev.close)return"上方流動性掃單";if(sl&&last.close>prev.close)return"下方流動性掃單";return"無明顯掃流動性"}
function trendline(cs){if(cs.length<20)return"趨勢線資料不足";const cl=cs.slice(-20).map(c=>c.close),x=cl.map((_,i)=>i),xm=x.reduce((a,b)=>a+b,0)/x.length,ym=cl.reduce((a,b)=>a+b,0)/cl.length,num=x.reduce((s,xi,i)=>s+(xi-xm)*(cl[i]-ym),0),den=x.reduce((s,xi)=>s+(xi-xm)**2,0),slope=den?num/den:0;if(slope>0.15*(ym/100))return"上升趨勢線有效";if(slope<-0.15*(ym/100))return"下降趨勢線有效";return"趨勢線偏平"}
function biasFromCandles(cs){const cl=cs.map(c=>c.close),p=cl.at(-1),m20=sma(cl,20).at(-1),m50=sma(cl,50).at(-1),rr=rsi(cl,14),mc=macd(cl),sl=cl.at(-1)-cl.slice(-6)[0];let bull=0,bear=0;if(p>m20)bull++;else bear++;if(p>m50)bull++;else bear++;if(sl>0)bull++;else bear++;if(mc?.macd>mc?.signal&&mc?.histogram>0)bull++;if(mc?.macd<mc?.signal&&mc?.histogram<0)bear++;if(rr>=55&&rr<=70)bull++;if(rr<=45&&rr>=30)bear++;let bias="中性";if(bull-bear>=1.5)bias="偏多";if(bear-bull>=1.5)bias="偏空";return{bias,bull,bear}}
function analyze(cs,higher=[]){const cl=cs.map(c=>c.close),price=cl.at(-1),ma20=sma(cl,20).at(-1),ma50=sma(cl,50).at(-1),rr=rsi(cl,14),mc=macd(cl),aa=atr(cs,14),lv=pivots(cs.slice(-120),price,aa),st=detectStructure(cs),vs=volState(cs),bs=breakout(cs,lv,aa),ls=liqSweep(cs,lv,aa),ts=trendline(cs),slope=cl.at(-1)-cl.slice(-6)[0];let bull=0,bear=0;if(price>ma20)bull++;else bear++;if(price>ma50)bull++;else bear++;if(slope>0)bull++;else bear++;if(mc?.macd>mc?.signal&&mc?.histogram>0)bull++;if(mc?.macd<mc?.signal&&mc?.histogram<0)bear++;if(rr>=55&&rr<=70)bull++;if(rr<=45&&rr>=30)bear++;if(st==="上升結構")bull++;if(st==="下降結構")bear++;if(bs==="向上突破")bull++;if(bs==="向下跌破")bear++;if(vs==="放量"&&slope>0)bull+=.5;if(vs==="放量"&&slope<0)bear+=.5;let bias="中性";if(bull-bear>=1.5)bias="偏多";if(bear-bull>=1.5)bias="偏空";
const higherBiases=higher.map(({interval,candles})=>({interval,...biasFromCandles(candles)})),hb=higherBiases.filter(x=>x.bias==="偏多").length,hr=higherBiases.filter(x=>x.bias==="偏空").length,confluence=hb>hr?"多週期偏多":hr>hb?"多週期偏空":"多週期分歧",entryScore=Number(Math.max(0,Math.min(10,4.5+Math.abs(bull-bear)+(((bias==="偏多"&&hb>=1)||(bias==="偏空"&&hr>=1))?1:0)+(bs==="區間內"?-.5:0))).toFixed(1));
let entryAdvice="先觀望",setup="等待更明確訊號",stopLoss=null,tp1=null,tp2=null,explanation="目前多空訊號接近，建議等待突破或回踩確認。";
if(bias==="偏多"){if(rr>68){entryAdvice="不建議追多";setup="等回踩";stopLoss=lv.structureSupportZone.low;tp1=lv.nearestResistance;tp2=lv.secondResistance;explanation="趨勢偏多，但 RSI 過熱，等回踩到結構支撐區會比直接追價更穩。"}else if(bs==="向上突破"){entryAdvice="可考慮突破跟隨";setup="等突破";stopLoss=lv.structureResistanceZone.low;tp1=lv.nearestResistance;tp2=lv.secondResistance;explanation="出現向上突破，若高週期也偏多，可用小倉位順勢跟隨。"}else{entryAdvice="可考慮分批做多";setup="等回踩";stopLoss=lv.structureSupportZone.low;tp1=lv.nearestResistance;tp2=lv.secondResistance;explanation="均線、結構與動能偏多，優先等支撐區回踩而不是追價。"}} 
if(bias==="偏空"){if(rr<32){entryAdvice="不建議追空";setup="等反彈";stopLoss=lv.structureResistanceZone.high;tp1=lv.nearestSupport;tp2=lv.secondSupport;explanation="趨勢偏空，但 RSI 偏低，直接追空容易被反彈掃到，等反彈壓力區較佳。"}else if(bs==="向下跌破"){entryAdvice="可考慮跌破跟隨";setup="等跌破";stopLoss=lv.structureSupportZone.high;tp1=lv.nearestSupport;tp2=lv.secondSupport;explanation="出現向下跌破，若高週期同步偏空，可考慮小倉位順勢。"}else{entryAdvice="可考慮分批做空";setup="等反彈";stopLoss=lv.structureResistanceZone.high;tp1=lv.nearestSupport;tp2=lv.secondSupport;explanation="價格位於均線下方且結構偏弱，優先等反彈壓力區，不建議在低位追空。"}}
const riskLevel=aa&&price?(aa/price>.025?"高":aa/price>.015?"中":"低"):"中",buf=Math.max((aa||price*.01)*.3,price*.002);
const tradePlan=bias==="偏多"?{entryZone:setup==="等突破"?`${fmt(lv.structureResistanceZone.low)} ~ ${fmt(lv.structureResistanceZone.high+buf)}`:`${fmt(lv.structureSupportZone.low)} ~ ${fmt(lv.structureSupportZone.high)}`,invalidation:fmt(lv.structureSupportZone.low-buf),target1:fmt(lv.nearestResistance),target2:fmt(lv.secondResistance)}:bias==="偏空"?{entryZone:setup==="等跌破"?`${fmt(lv.structureSupportZone.low-buf)} ~ ${fmt(lv.structureSupportZone.high)}`:`${fmt(lv.structureResistanceZone.low)} ~ ${fmt(lv.structureResistanceZone.high)}`,invalidation:fmt(lv.structureResistanceZone.high+buf),target1:fmt(lv.nearestSupport),target2:fmt(lv.secondSupport)}:{entryZone:"等待突破或回踩確認",invalidation:"-",target1:fmt(lv.nearestResistance),target2:fmt(lv.secondSupport)};
const aiSummary=`目前偏向${bias}，結構為${st}，當前屬於${bs}${confluence!=="多週期分歧"?"，"+confluence:""}${vs!=="一般"?"，"+vs:""}${ls!=="無明顯掃流動性"?"，"+ls:""}${ts!=="趨勢線偏平"?"，"+ts:""}，策略以${setup}為主。`;
return{price,ma20,ma50,rsi:rr,macd:mc,atr:aa,bias,entryAdvice,setup,stopLoss,takeProfit1:tp1,takeProfit2:tp2,explanation,bullScore:bull,bearScore:bear,levels:lv,higherBiases,confluence,entryScore,riskLevel,structure:st,breakoutState:bs,volumeState:vs,tradePlan,liquiditySweep:ls,trendlineState:ts,aiSummary}}
async function fetchK(symbol,interval,limit=200){const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=${limit}`);if(!r.ok)throw new Error("無法取得價格資料，請稍後再試。");const d=await r.json();return d.map(row=>({openTime:row[0],open:+row[1],high:+row[2],low:+row[3],close:+row[4],volume:+row[5]}))}
function Kpi({title,value,helper}){return <div className="kpi"><div className="title">{title}</div><div className="value">{value}</div><small>{helper}</small></div>}
function Tip({active,payload,label,symbol}){if(!active||!payload?.length)return null;const row=payload[0].payload,d=symbol==="BTCUSDT"?0:2;return <div className="card" style={{padding:12,borderRadius:16}}><div style={{fontWeight:700,marginBottom:6}}>{label}</div><div>開盤：{fmt(row.open,d)}</div><div>最高：{fmt(row.high,d)}</div><div>最低：{fmt(row.low,d)}</div><div>收盤：{fmt(row.close,d)}</div><div>MA20：{fmt(row.ma20,d)}</div><div>MA50：{fmt(row.ma50,d)}</div><div>成交量：{fmt(row.volume,2)}</div></div>}
export default function App(){useEffect(()=>{try{registerSW({immediate:true})}catch{}},[]);const [symbol,setSymbol]=useState("SOLUSDT"),[interval,setInterval]=useState("15m"),[candles,setCandles]=useState([]),[analysis,setAnalysis]=useState(null),[loading,setLoading]=useState(false),[updated,setUpdated]=useState(""),[error,setError]=useState("");
const loadData=async()=>{setLoading(true);setError("");try{const rows=await fetchK(symbol,interval,200);const higher=await Promise.all((HIGHER_INTERVAL_MAP[interval]||[]).map(async tf=>({interval:tf,candles:await fetchK(symbol,tf,200)})));setCandles(rows);setAnalysis(analyze(rows,higher));setUpdated(new Date().toLocaleString())}catch(e){setError(e.message||"讀取失敗")}finally{setLoading(false)}};
useEffect(()=>{loadData()},[symbol,interval]);useEffect(()=>{const t=setInterval(loadData,30000);return()=>clearInterval(t)},[symbol,interval]);
const chartData=useMemo(()=>{if(!candles.length)return[];const cl=candles.map(c=>c.close),m20=sma(cl,20),m50=sma(cl,50);return candles.slice(-60).map((c,idx,arr)=>{const oi=candles.length-arr.length+idx;return{time:fmtTime(c.openTime,interval),...c,ma20:m20[oi],ma50:m50[oi],bullish:c.close>=c.open}})},[candles,interval]); const d=symbol==="BTCUSDT"?0:2;
const badge=analysis?.bias==="偏多"?"bull":analysis?.bias==="偏空"?"bear":"flat";
return <div className="app">
<div className="twocol">
<div className="card"><div style={{display:"flex",alignItems:"center",gap:10,fontSize:28,fontWeight:800,marginBottom:16}}><Activity size={28}/>Crypto Signal Pro</div>
<div className="controls"><div><div className="label">幣種</div><select className="select" value={symbol} onChange={e=>setSymbol(e.target.value)}>{SYMBOL_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div><div><div className="label">週期</div><select className="select" value={interval} onChange={e=>setInterval(e.target.value)}>{INTERVAL_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></div><div><div className="label">操作</div><button className="button" onClick={loadData}><RefreshCw size={16} style={{verticalAlign:"text-bottom",marginRight:8}}/>{loading?"分析中":"重新分析"}</button></div></div>
<div className="note" style={{marginTop:14}}>自動抓 Binance 公開 K 線資料，整合 MA、RSI、MACD、ATR、結構、突破、量能、多週期共振與 AI 交易計畫。最後更新：{updated||"-"}</div>{error?<div className="note" style={{marginTop:12,background:"#fee2e2",color:"#991b1b"}}>{error}</div>:null}</div>
<div className="card"><div className="row" style={{justifyContent:"space-between",alignItems:"center"}}><div className="muted">趨勢偏向</div><span className={`badge ${badge}`}>{analysis?.bias||"讀取中"}</span></div>
<div className="zone" style={{marginTop:12}}><div className="label">是否適合進場</div><div style={{fontSize:26,fontWeight:800}}>{analysis?.entryAdvice||"-"}</div></div>
<div className="zone" style={{marginTop:12}}><div className="label">較佳策略</div><div style={{fontSize:22,fontWeight:800}}>{analysis?.setup||"-"}</div></div>
<div className="zone" style={{marginTop:12}}><div className="label">進場評分 / 風險等級 / 共振</div><div style={{fontSize:22,fontWeight:800}}>{analysis?.entryScore||"-"} / 10 ・ {analysis?.riskLevel||"-"} ・ {analysis?.confluence||"-"}</div></div>
<div className="ai" style={{marginTop:12}}><div style={{fontSize:12,textTransform:"uppercase",letterSpacing:1,color:"#cbd5e1",marginBottom:8}}>AI 綜合判斷</div><div>{analysis?.aiSummary||"等待資料中..."}</div></div></div></div>
<div className="kpis" style={{marginTop:16}}>
<Kpi title="現價" value={fmt(analysis?.price,d)} helper="即時收盤價"/><Kpi title="MA20" value={fmt(analysis?.ma20,d)} helper="20 均線"/><Kpi title="MA50" value={fmt(analysis?.ma50,d)} helper="50 均線"/><Kpi title="RSI" value={fmt(analysis?.rsi,2)} helper="14 週期"/><Kpi title="MACD 柱狀體" value={fmt(analysis?.macd?.histogram,4)} helper="正值偏強"/><Kpi title="結構" value={analysis?.structure||"-"} helper="上升 / 下降 / 盤整"/><Kpi title="突破狀態" value={analysis?.breakoutState||"-"} helper="突破 / 回踩 / 區間"/><Kpi title="量能狀態" value={analysis?.volumeState||"-"} helper="放量 / 量縮 / 一般"/><Kpi title="掃流動性" value={analysis?.liquiditySweep||"-"} helper="掃高 / 掃低"/><Kpi title="趨勢線" value={analysis?.trendlineState||"-"} helper="趨勢線狀態"/>
</div>
<div className="card" style={{marginTop:16}}><div style={{fontWeight:800,marginBottom:12}}>圖表、均線與支撐壓力</div><div style={{width:"100%",height:380,background:"#f1f5f9",borderRadius:18,padding:8}}>
<ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{top:12,right:12,left:4,bottom:8}}><CartesianGrid strokeDasharray="3 3" stroke="#cbd5e1"/><XAxis dataKey="time" minTickGap={24} tick={{fontSize:12}}/><YAxis yAxisId="left" domain={["auto","auto"]} tick={{fontSize:12}} width={70}/><YAxis yAxisId="right" orientation="right" tick={false} hide/><Tooltip content={<Tip symbol={symbol}/>}/><ReferenceArea yAxisId="left" y1={analysis?.levels?.structureSupportZone?.low} y2={analysis?.levels?.structureSupportZone?.high} fill="#16a34a" fillOpacity={0.08}/><ReferenceArea yAxisId="left" y1={analysis?.levels?.structureResistanceZone?.low} y2={analysis?.levels?.structureResistanceZone?.high} fill="#dc2626" fillOpacity={0.08}/><ReferenceLine yAxisId="left" y={analysis?.price} stroke="#0f172a" strokeDasharray="4 4"/><Bar yAxisId="right" dataKey="volume" opacity={0.22} radius={[3,3,0,0]}>{chartData.map((e,i)=><Cell key={i} fill={e.bullish?"#16a34a":"#dc2626"}/>)}</Bar><Bar yAxisId="left" dataKey="close" opacity={0.85}>{chartData.map((e,i)=><Cell key={i} fill={e.bullish?"#16a34a":"#dc2626"}/>)}</Bar><Line yAxisId="left" type="monotone" dataKey="ma20" dot={false} strokeWidth={2} stroke="#a855f7"/><Line yAxisId="left" type="monotone" dataKey="ma50" dot={false} strokeWidth={2} stroke="#eab308"/></ComposedChart></ResponsiveContainer></div><div className="muted" style={{marginTop:10}}>綠色區是結構支撐，紅色區是結構壓力，虛線是現價。這裡用色塊 K 線替代，可先直接用來看趨勢與區間。</div></div>
<div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",marginTop:16}}>
<div className="card"><div style={{fontWeight:800,marginBottom:12}}>交易建議</div><div className="subgrid"><div className="zone"><div className="label">建議方式</div><div style={{fontWeight:800,fontSize:20}}>{analysis?.setup||"-"}</div></div><div className="zone"><div className="label">止損</div><div style={{fontWeight:800,fontSize:20}}>{fmt(analysis?.stopLoss,d)}</div></div><div className="zone"><div className="label">止盈</div><div style={{fontWeight:800,fontSize:20}}>{fmt(analysis?.takeProfit1,d)} / {fmt(analysis?.takeProfit2,d)}</div></div><div className="zone"><div className="label">最近 K 線區間</div><div style={{fontWeight:800,fontSize:20}}>{fmt(candles.at(-1)?.low,d)} ~ {fmt(candles.at(-1)?.high,d)}</div></div></div><div className="note" style={{marginTop:12}}><div>• 偏多：優先等回踩支撐或突破確認，不建議在 RSI 過熱時追價。</div><div>• 偏空：優先等反彈壓力或跌破確認，不建議在 RSI 過低時追空。</div><div>• 止損 / 止盈是依最近支撐壓力自動估算，適合當作初步參考。</div></div><div className="subgrid" style={{marginTop:12}}><div className="zone"><div className="label">建議進場區</div><div style={{fontWeight:800,fontSize:18}}>{analysis?.tradePlan?.entryZone||"-"}</div></div><div className="zone"><div className="label">失效位</div><div style={{fontWeight:800,fontSize:18}}>{analysis?.tradePlan?.invalidation||"-"}</div></div><div className="zone"><div className="label">目標一</div><div style={{fontWeight:800,fontSize:18}}>{analysis?.tradePlan?.target1||"-"}</div></div><div className="zone"><div className="label">目標二</div><div style={{fontWeight:800,fontSize:18}}>{analysis?.tradePlan?.target2||"-"}</div></div></div></div>
<div className="card"><div style={{fontWeight:800,marginBottom:12}}>資料摘要</div><div className="subgrid"><div className="zone"><div className="label">短線支撐區</div><div style={{fontWeight:800,fontSize:18}}>{fmt(analysis?.levels?.shortSupportZone?.low,d)} ~ {fmt(analysis?.levels?.shortSupportZone?.high,d)}</div></div><div className="zone"><div className="label">短線壓力區</div><div style={{fontWeight:800,fontSize:18}}>{fmt(analysis?.levels?.shortResistanceZone?.low,d)} ~ {fmt(analysis?.levels?.shortResistanceZone?.high,d)}</div></div><div className="zone"><div className="label">結構支撐區</div><div style={{fontWeight:800,fontSize:18}}>{fmt(analysis?.levels?.structureSupportZone?.low,d)} ~ {fmt(analysis?.levels?.structureSupportZone?.high,d)}</div></div><div className="zone"><div className="label">結構壓力區</div><div style={{fontWeight:800,fontSize:18}}>{fmt(analysis?.levels?.structureResistanceZone?.low,d)} ~ {fmt(analysis?.levels?.structureResistanceZone?.high,d)}</div></div><div className="zone"><div className="label">ATR 波動</div><div style={{fontWeight:800,fontSize:18}}>{fmt(analysis?.atr,d)}</div></div></div><div className="note" style={{marginTop:12}}><div style={{fontWeight:700,color:"#334155",marginBottom:6}}>AI 訊號細節</div><div>多方分數：{fmt(analysis?.bullScore,1)}</div><div>空方分數：{fmt(analysis?.bearScore,1)}</div><div>成交量：{fmt(candles.at(-1)?.volume,2)}</div><div style={{marginTop:10,fontWeight:700,color:"#334155"}}>高週期同步</div>{(analysis?.higherBiases||[]).map(item=><div key={item.interval} style={{display:"flex",justifyContent:"space-between",background:"#f8fafc",padding:"10px 12px",borderRadius:12,marginTop:8}}><span>{item.interval}</span><span>{item.bias}</span></div>)}</div></div></div>
</div>}
